#############################################################################
# Makefile for building: QtSpecem.app/Contents/MacOS/QtSpecem
# Generated by qmake (3.1) (Qt 5.13.1)
# Project:  QtSpecem.pro
# Template: app
# Command: /Users/ruiribeiro/Qt/5.13.1/clang_64/bin/qmake -o Makefile QtSpecem.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.13.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt/5.13.1/clang_64/mkspecs/macx-clang -F/Users/ruiribeiro/Qt/5.13.1/clang_64/lib
QMAKE         = /Users/ruiribeiro/Qt/5.13.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/ruiribeiro/Qt/5.13.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/ruiribeiro/Qt/5.13.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = QtSpecem1.0.0
DISTDIR = /Users/ruiribeiro/Desktop/z80/QtSpecem/.tmp/QtSpecem1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/ruiribeiro/Qt/5.13.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/ruiribeiro/Qt/5.13.1/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		QtSpecem.cpp \
		emul/error.c \
		emul/initmem.c \
		emul/sna_load.c \
		emul/sna_save.c \
		emul/video.c \
		z80core/bits.c \
		z80core/callret.c \
		z80core/exctranf.c \
		z80core/flags.c \
		z80core/init.c \
		z80core/inout.c \
		z80core/intr.c \
		z80core/jump.c \
		z80core/kernel.c \
		z80core/ld16bits.c \
		z80core/ld8bits.c \
		z80core/math16bi.c \
		z80core/math8bit.c \
		z80core/mem.c \
		z80core/misc.c \
		z80core/ndebgz80.c \
		z80core/ports.c \
		z80core/rotate.c \
		z80core/shutdown.c \
		z80core/stack.c qrc_QtSpecem.cpp \
		moc_QtSpecem.cpp
OBJECTS       = main.o \
		QtSpecem.o \
		error.o \
		initmem.o \
		sna_load.o \
		sna_save.o \
		video.o \
		bits.o \
		callret.o \
		exctranf.o \
		flags.o \
		init.o \
		inout.o \
		intr.o \
		jump.o \
		kernel.o \
		ld16bits.o \
		ld8bits.o \
		math16bi.o \
		math8bit.o \
		mem.o \
		misc.o \
		ndebgz80.o \
		ports.o \
		rotate.o \
		shutdown.o \
		stack.o \
		qrc_QtSpecem.o \
		moc_QtSpecem.o
DIST          = ../../../Qt/5.13.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.13.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/mac.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/lex.prf \
		QtSpecem.pro QtSpecem.h \
		h/quirks.h \
		h/snap.h \
		z80core/env.h \
		z80core/iglobal.h \
		z80core/ivars.h \
		z80core/z80.h main.cpp \
		QtSpecem.cpp \
		emul/error.c \
		emul/initmem.c \
		emul/sna_load.c \
		emul/sna_save.c \
		emul/video.c \
		z80core/bits.c \
		z80core/callret.c \
		z80core/exctranf.c \
		z80core/flags.c \
		z80core/init.c \
		z80core/inout.c \
		z80core/intr.c \
		z80core/jump.c \
		z80core/kernel.c \
		z80core/ld16bits.c \
		z80core/ld8bits.c \
		z80core/math16bi.c \
		z80core/math8bit.c \
		z80core/mem.c \
		z80core/misc.c \
		z80core/ndebgz80.c \
		z80core/ports.c \
		z80core/rotate.c \
		z80core/shutdown.c \
		z80core/stack.c
QMAKE_TARGET  = QtSpecem
DESTDIR       = 
TARGET        = QtSpecem.app/Contents/MacOS/QtSpecem

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/ruiribeiro/Desktop/z80/QtSpecem/QtSpecem.pro


include /Users/ruiribeiro/Qt/5.13.1/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

QtSpecem.app/Contents/MacOS/QtSpecem:  $(OBJECTS)  
	@test -d QtSpecem.app/Contents/MacOS/ || mkdir -p QtSpecem.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QtSpecem.pro ../../../Qt/5.13.1/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.13.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.13.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.13.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/mac.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.13.1/clang_64/mkspecs/features/lex.prf \
		QtSpecem.pro \
		QtSpecem.qrc \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.13.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile QtSpecem.pro
../../../Qt/5.13.1/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.13.1/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.13.1/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.13.1/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.13.1/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.13.1/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.13.1/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.13.1/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.13.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.13.1/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.13.1/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.13.1/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.13.1/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.13.1/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.13.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.13.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/toolchain.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/mac/mac.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.13.1/clang_64/mkspecs/features/lex.prf:
QtSpecem.pro:
QtSpecem.qrc:
../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt/5.13.1/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.13.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile QtSpecem.pro

qmake_all: FORCE

QtSpecem.app/Contents/PkgInfo: 
	@test -d QtSpecem.app/Contents || mkdir -p QtSpecem.app/Contents
	@$(DEL_FILE) QtSpecem.app/Contents/PkgInfo
	@echo "APPL????" > QtSpecem.app/Contents/PkgInfo
QtSpecem.app/Contents/Resources/empty.lproj: 
	@test -d QtSpecem.app/Contents/Resources || mkdir -p QtSpecem.app/Contents/Resources
	@touch QtSpecem.app/Contents/Resources/empty.lproj
	
QtSpecem.app/Contents/Info.plist: 
	@test -d QtSpecem.app/Contents || mkdir -p QtSpecem.app/Contents
	@$(DEL_FILE) QtSpecem.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.QtSpecem,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.QtSpecem,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,icon.icns,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},icon.icns,g" -e "s,@EXECUTABLE@,QtSpecem,g" -e "s,@LIBRARY@,QtSpecem,g" -e "s,\$${EXECUTABLE_NAME},QtSpecem,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../Qt/5.13.1/clang_64/mkspecs/macx-clang/Info.plist.app >QtSpecem.app/Contents/Info.plist
QtSpecem.app/Contents/Resources/icon.icns: icon.icns
	@test -d QtSpecem.app/Contents/Resources/ || mkdir -p QtSpecem.app/Contents/Resources/
	@$(DEL_FILE) QtSpecem.app/Contents/Resources/icon.icns
	@$(COPY_FILE) icon.icns QtSpecem.app/Contents/Resources/icon.icns

all: Makefile \
		QtSpecem.app/Contents/PkgInfo \
		QtSpecem.app/Contents/Resources/empty.lproj \
		QtSpecem.app/Contents/Info.plist \
		QtSpecem.app/Contents/Resources/icon.icns QtSpecem.app/Contents/MacOS/QtSpecem

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents QtSpecem.qrc QtSpecem.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/5.13.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents QtSpecem.h h/quirks.h h/snap.h z80core/env.h z80core/iglobal.h z80core/ivars.h z80core/z80.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp QtSpecem.cpp emul/error.c emul/initmem.c emul/sna_load.c emul/sna_save.c emul/video.c z80core/bits.c z80core/callret.c z80core/exctranf.c z80core/flags.c z80core/init.c z80core/inout.c z80core/intr.c z80core/jump.c z80core/kernel.c z80core/ld16bits.c z80core/ld8bits.c z80core/math16bi.c z80core/math8bit.c z80core/mem.c z80core/misc.c z80core/ndebgz80.c z80core/ports.c z80core/rotate.c z80core/shutdown.c z80core/stack.c $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r QtSpecem.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_QtSpecem.cpp qrc_QtSpecem.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_QtSpecem.cpp qrc_QtSpecem.cpp
qrc_QtSpecem.cpp: QtSpecem.qrc \
		../../../Qt/5.13.1/clang_64/bin/rcc \
		rom/spectrum.rom
	/Users/ruiribeiro/Qt/5.13.1/clang_64/bin/rcc -name QtSpecem QtSpecem.qrc -o qrc_QtSpecem.cpp

qrc_QtSpecem.cpp: QtSpecem.qrc \
		../../../Qt/5.13.1/clang_64/bin/rcc \
		rom/spectrum.rom
	/Users/ruiribeiro/Qt/5.13.1/clang_64/bin/rcc -name QtSpecem QtSpecem.qrc -o qrc_QtSpecem.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/5.13.1/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h ../../../Qt/5.13.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_QtSpecem.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_QtSpecem.cpp
moc_QtSpecem.cpp: QtSpecem.h \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtguiglobal.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengltextureblitter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		moc_predefs.h \
		../../../Qt/5.13.1/clang_64/bin/moc
	/Users/ruiribeiro/Qt/5.13.1/clang_64/bin/moc $(DEFINES) --include /Users/ruiribeiro/Desktop/z80/QtSpecem/moc_predefs.h -I/Users/ruiribeiro/Qt/5.13.1/clang_64/mkspecs/macx-clang -I/Users/ruiribeiro/Desktop/z80/QtSpecem -I/Users/ruiribeiro/Desktop/z80/QtSpecem -I/Users/ruiribeiro/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/ruiribeiro/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers -I/Users/ruiribeiro/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Users/ruiribeiro/Qt/5.13.1/clang_64/lib QtSpecem.h -o moc_QtSpecem.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp QtSpecem.h \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtguiglobal.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengltextureblitter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtguiversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

QtSpecem.o: QtSpecem.cpp QtSpecem.h \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtguiglobal.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengltextureblitter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../../Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtSpecem.o QtSpecem.cpp

error.o: emul/error.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o error.o emul/error.c

initmem.o: emul/initmem.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o initmem.o emul/initmem.c

sna_load.o: emul/sna_load.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h \
		h/snap.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sna_load.o emul/sna_load.c

sna_save.o: emul/sna_save.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h \
		h/snap.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sna_save.o emul/sna_save.c

video.o: emul/video.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o video.o emul/video.c

bits.o: z80core/bits.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o bits.o z80core/bits.c

callret.o: z80core/callret.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o callret.o z80core/callret.c

exctranf.o: z80core/exctranf.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o exctranf.o z80core/exctranf.c

flags.o: z80core/flags.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o flags.o z80core/flags.c

init.o: z80core/init.c z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o init.o z80core/init.c

inout.o: z80core/inout.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o inout.o z80core/inout.c

intr.o: z80core/intr.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o intr.o z80core/intr.c

jump.o: z80core/jump.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jump.o z80core/jump.c

kernel.o: z80core/kernel.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h \
		z80core/ivars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o kernel.o z80core/kernel.c

ld16bits.o: z80core/ld16bits.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ld16bits.o z80core/ld16bits.c

ld8bits.o: z80core/ld8bits.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ld8bits.o z80core/ld8bits.c

math16bi.o: z80core/math16bi.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o math16bi.o z80core/math16bi.c

math8bit.o: z80core/math8bit.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o math8bit.o z80core/math8bit.c

mem.o: z80core/mem.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o mem.o z80core/mem.c

misc.o: z80core/misc.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o misc.o z80core/misc.c

ndebgz80.o: z80core/ndebgz80.c h/quirks.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ndebgz80.o z80core/ndebgz80.c

ports.o: z80core/ports.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ports.o z80core/ports.c

rotate.o: z80core/rotate.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o rotate.o z80core/rotate.c

shutdown.o: z80core/shutdown.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o shutdown.o z80core/shutdown.c

stack.o: z80core/stack.c z80core/env.h \
		z80core/z80.h \
		h/quirks.h \
		z80core/iglobal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o stack.o z80core/stack.c

qrc_QtSpecem.o: qrc_QtSpecem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_QtSpecem.o qrc_QtSpecem.cpp

moc_QtSpecem.o: moc_QtSpecem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtSpecem.o moc_QtSpecem.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

